source 'https://rubygems.org'

gem 'capybara', '~> 2.18.0'
gem 'cucumber', '~> 3.1'
gem 'faker'
gem 'httparty'
gem 'pry', '~> 0.11'
gem 'rspec', '~> 3.6.0'
gem 'selenium-webdriver', '~> 3.9'
gem 'site_prism', '~> 2.9'
